baseURL = "https://www.thebalanceffxiv.com/"
languageCode = "en-us"
title = "Balance Guides"
theme = "glam"

[params]
  maxLevel = 80
  maxTierGearsets = 8
  maxUltimateGearsets = 4
  maxGearsets = 12
  discord = 'discord.gg/thebalanceffxiv'
  copyrightMessage = '© SQUARE ENIX CO., LTD. All Rights Reserved | FINAL FANTASY is a registered trademark of Square Enix Holdings Co., Ltd. | All content © their respective authors | The Balance is a non-profit community-owned website.'

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1

[menu]
  [[menu.main]]
    identifier = 'jobs'
    name = 'Combat Jobs'
    url = '#'
    weight = 10
  [[menu.main]]
    identifier = 'other-jobs'
    name = 'Other Jobs'
    url = '#'
    weight = 20
  [[menu.main]]
    identifier = 'encounters'
    name = 'Fight Encounters'
    url = '#'
    weight = 30
  [[menu.main]]
    identifier = 'tools'
    name = 'Tools'
    url = '#'
    weight = 40
  [[menu.main]]
    identifier = 'other-guides'
    name = 'Other Guides'
    url = '#'
    weight = 50
  [[menu.header]]
    identifier = 'news'
    name = 'Newsfeed'
    url = '#'
    weight = 60
  [[menu.footer]]
    identifier = 'info'
    name = 'Info'
    url = '#'
    weight = 60
